### PR TITLE
updated documentation and polished text

### PR DESCRIPTION
**Pull request by dgarijo**

### CODE REVIEW

**Comment by dgarijo** [comment]
I tried to use real examples @proycon. Please have a look when you have the chance.

**Comment by proycon** [comment]
Looks good! Good improvements and clarifications. Using real-life examples is indeed better.

I did some adaptations based on your feedback in #7 #9.

I also adapted example A somewhat:

* version should typically be a separate property, not part of the name. I also
  moved it to the source code level, as the entire code base corresponds
  to that version (ideally properly git tagged of course).
  It may be replicated at the targetProduct level, but that'd be a bit redundant.

* I added an executableName for both the command line tool and the
  library. For the former the version is part of the name because that's
  simply how your software ships if I interpreted your README correctly.

* I didn't change the runtimePlatform (Linux) since I don't know your
  software but this might be too  narrowly defined for this particular
  java software?

**Comment by proycon** [comment]
Speaking of real-life examples, just over a week ago I did some software release of our main software stack, and I already (prematurely) included `codemeta.json` files that comply to what I've been proposing (and also #5):

* https://github.com/LanguageMachines/frog/blob/master/codemeta.json
* https://github.com/LanguageMachines/ucto/blob/master/codemeta.json
* https://github.com/LanguageMachines/timbl/blob/master/codemeta.json

**Comment by dgarijo** [comment]
I will continue reviewing this when I have a chance. I left some comments (I have avoided the data produces and data uses conversation for now, because I am still have concerns :( )
Btw, if you already have full examples, please add them to the repo. We can have a link at the end of the readme with something like "please have a look at additional examples in BLAH, and point to them"

**Comment by proycon** [comment]
> I will continue reviewing this when I have a chance. I left some comments (I have avoided the data produces and data uses conversation for now, because I am still have concerns :( )

Thanks, I'll shortly reply to those in the other PR

> Btw, if you already have full examples, please add them to the repo. We can have a link at the end of the readme with something like "please have a look at additional examples in BLAH, and point to them"

Good idea, I'll do that

**Comment by dgarijo** [comment]
Just for my clarity, I am going to merge this and then we can continue the discussion. Otherwise I find it challenging to see who added what on top of which example

**Pull request merged**
