### PR TITLE
Worked out documentation and examples for software type profile 

### PR DESCRIPTION
**Pull request by proycon**
I worked out some unified documentation for what we currently have so people don't have to wade through various issues in the codemeta issue tracker (codemeta/codemeta#271, codemeta/codemeta#267)

### CODE REVIEW

**Comment by proycon** [comment]
@dgarijo Do you have a chance to take a look at this?

**Comment by dgarijo** [comment]
Sorry for the delay, Maarten!
I will have a look ASAP.
Daniel

**Comment by dgarijo** [comment]
I know I am still running late, the end of the semester has been
complicated. I plan to review things thoroughly this week.
Thanks for your patience.

**Comment by dgarijo** [comment]
I have some comments, let me merge and do a new PR with suggestions so we can discuss them. For the most part, it looks good. I want to have a section with the definitions so we enable content negotiation

**Review by dgarijo — APPROVED** [review]

**Pull request merged**
